using System;
using System.Collections.Generic;
using System.Text;

namespace Cybersecurity_Awareness_GUI
{
    // Same logic as console app 
    // replaced console.writeline to string returns
    internal class DictionaryResponces
    {
        public Dictionary<string, string> keywordResponses = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            // Passwords
            {"password", "A strong password is your first line of defence. Aim for at least 12 characters and mix uppercase letters," +
                    " numbers, and symbols. Avoid using names, birthdays, or common words because attackers use automated tools that guess those instantly."},

            {"passwords", "A strong password is your first line of defence. Aim for at least 12 characters and mix uppercase letters," +
                    " numbers, and symbols. Avoid using names, birthdays, or common words because attackers use automated tools that guess those instantly."},

            {"passphrase", "A passphrase is a sequence of random words, like 'BlueCoffeeRocket42!'. They're longer than typical passwords," +
                    " which makes them harder to crack, but easier for you to remember. Many security experts now prefer them over complex short passwords."},

            {"2fa", "Two-factor authentication (2FA) adds a second verification step which is usually a code sent to your phone or generated by an app. " +
                    "Even if someone steals your password, they still can't get in without that second factor."},

            {"two factor", "Two-factor authentication (2FA) adds a second verification which usually a code sent to your phone or generated by an app." +
                    " Even if someone steals your password, they still can't get in without that second factor."},

            {"authentication", "Authentication is how a system verifies who you are. The strongest approach combines something you know (password)," +
                    " something you have (phone), and something you are (fingerprint). Using more than one of these is called multi-factor authentication."},

            {"manager", "A password manager stores all your passwords in an encrypted vault." +
                    " You only need to remember one strong master password."},

            // Phishing
            {"phishing", "Phishing is when attackers send fake emails or messages pretending to be someone you trust." +
                    " Their goal is to trick you into clicking a link or entering your credentials. " +
                    "Always verify the sender's actual email address, not just the display name."},

            {"email", "Suspicious emails are one of the most common ways attackers get in. " +
                    "Watch for urgent language, mismatched sender addresses, unexpected attachments," +
                    " and links that don't match the site they claim to go to." +
                    " When in doubt, contact the sender directly through a known channel."},

            {"link", "Before clicking any link, hover over it to preview the actual URL. " +
                    "Attackers often use URLs that look close to the real thing. " +
                    "If you're unsure, go directly to the website by typing the address yourself."},

            {"scam", "Scams often create a false sense of urgency, e.g 'Act now or your account will be closed!' " +
                    "Legitimate companies rarely pressure you like this. Slow down, question the source, " +
                    "and verify independently before taking any action."},

            {"social engineering", "Social engineering manipulates people rather than systems. " +
                    "An attacker might call pretending to be IT support, or send a message impersonating your boss. " +
                    "They exploit trust and urgency. Always verify identities through official channels before sharing sensitive information."},

            {"spear phishing", "Spear phishing is a targeted form of phishing where the attacker personalises the message using details about you." +
                    " It's much harder to spot than generic phishing because it feels relevant and familiar."},

            // Safe Browsing
            {"browsing", "Safe browsing starts with checking for 'https://' in the URL bar and a padlock icon. " +
                    "This means your connection is encrypted. Avoid entering personal information on sites that only use 'http://' — " +
                    "your data could be intercepted."},

            {"https", "HTTPS encrypts the data between your browser and the website, " +
                    "protecting it from being read or tampered with in transit. The padlock icon in your browser confirms this. " +
                    "It doesn't mean the site is trustworthy, but it does mean your connection is private."},

            {"vpn", "A VPN (Virtual Private Network) encrypts your internet traffic and hides your IP address. " +
                    "It's especially useful on public Wi-Fi, where your data could otherwise be intercepted. " +
                    "Look for reputable, no-log VPN providers rather than free ones, which may sell your data."},

            {"public wifi", "Public Wi-Fi networks are convenient but risky. " +
                    "Attackers on the same network can intercept unencrypted traffic. Avoid logging into sensitive accounts on public Wi-Fi, " +
                    "and use a VPN if you need to. Mobile data is generally safer than open hotspots."},

            {"wifi", "Public Wi-Fi networks are convenient but risky. Attackers on the same network can intercept unencrypted traffic. " +
                    "Avoid logging into sensitive accounts on public Wi-Fi, and use a VPN if you need to. " +
                    "Mobile data is generally safer than open hotspots."},

            {"update", "Software updates often contain security patches for vulnerabilities that attackers actively exploit. " +
                    "Delaying updates leaves you exposed. Enable automatic updates where possible — for your OS, browser, and apps " +
                    "— so you're always protected."},

            {"cookie", "Cookies are small files websites store on your browser to remember you. While useful, " +
                    "third-party tracking cookies follow you across sites. Regularly clear your cookies, " +
                    "or use browser settings to block third-party cookies for better privacy."},

            {"privacy", "Online privacy means controlling what information you share and with whom." +
                    " Use privacy-focused browsers or settings, review app permissions, and be cautious about oversharing " +
                    "on social media — attackers often use public information to craft convincing scams."},

            {"download", "Only download software from official or well-known sources. Malicious files are often disguised as " +
                    "free games, tools, or cracked software. If a download asks you to disable your antivirus " +
                    "or ignore security warnings, that's a strong red flag."},
        };

        // Returns a response string instead of writing to Console.
        public string HandleFreeText(string input)
        {
            // Check if the input contains any of the keywords in the dictionary (case-insensitive)
            foreach (var entry in keywordResponses)
            {
                if (input.IndexOf(entry.Key, StringComparison.OrdinalIgnoreCase) >= 0)
                    return entry.Value;
            }

            return "Hmm, I'm not sure about that one. I currently know about passwords, " +
                   "phishing, and safe browsing. Try asking about one of those topics, or use " +
                   "the menu buttons to explore what I can help with.";
        }


    }
}
