using System;
using System.Collections.Generic;
using System.Text;

namespace Cybersecurity_Awareness_GUI
{
    internal class MenueTopicInterface
    {
        //identical to orignial console app
        //change from console.app to string

        // all information related to passwords
        public string PasswordInfo() =>
            "── Passwords & Authentication ──\n\n" +
            "Strong Passwords\n" +
            "A strong password should be at least 12 characters long and mix uppercase letters, " +
            "lowercase letters, numbers, and symbols. Avoid using common words, phrases, or easily " +
            "guessable information like birthdays or pet names.\n\n" +
            "Passphrases\n" +
            "Consider using a passphrase — a sequence of words that is easy for you to remember " +
            "but hard for others to guess. Example: BlueCoffeeRocket42!\n\n" +
            "Two-Factor Authentication (2FA)\n" +
            "2FA adds a second verification step after your password — a code sent to your phone " +
            "or generated by an app. Even if your password is stolen, your account stays protected.\n\n" +
            "Password Manager\n" +
            "A password manager stores all your passwords in an encrypted vault. You only need to " +
            "remember one strong master password, making it easy to use a unique, complex password " +
            "for every site without memorising them all.";

        // all information based on phishing
        // 
        public string PhishingInfo() => 
            "── Phishing & Social Engineering ──\n\n" +
            "What is Phishing?\n" +
            "Phishing is when attackers send fake emails or messages pretending to be someone you trust. " +
            "Their goal is to trick you into clicking a link or handing over your credentials.\n\n" +
            "How to Spot a Phishing Email\n" +
            "Watch for urgent language, mismatched sender addresses, unexpected attachments, " +
            "and links that don't match the site they claim to go to. When in doubt, contact " +
            "the sender directly through a known channel.\n\n" +
            "Spear Phishing\n" +
            "Spear phishing is a targeted attack where the message is personalised using details " +
            "about you. Be extra cautious with unexpected requests, even if they seem to come from " +
            "someone you know.\n\n" +
            "Social Engineering\n" +
            "Social engineering manipulates people rather than systems. Attackers exploit trust and " +
            "urgency — always verify identities through official channels before sharing sensitive information.";

        // all information on browsing
        //

        public string BrowsingInfo() =>
            "── Safe Browsing Habits ──\n\n" +
            "HTTPS and the Padlock\n" +
            "Always check for 'https://' and a padlock icon in your browser's address bar. " +
            "This indicates that the connection is encrypted and your data is private in transit.\n\n" +
            "Public Wi-Fi Risks\n" +
            "Public Wi-Fi is convenient but risky. Attackers on the same network can intercept " +
            "unencrypted traffic. Avoid logging into sensitive accounts on open hotspots.\n\n" +
            "VPNs\n" +
            "A Virtual Private Network encrypts your internet traffic and masks your IP address. " +
            "Especially useful on public Wi-Fi — choose a reputable, no-log provider.\n\n" +
            "Software Updates\n" +
            "Updates frequently include security patches for vulnerabilities that attackers actively " +
            "exploit. Enable automatic updates for your OS, browser, and apps.\n\n" +
            "Safe Downloads\n" +
            "Only download software from official or well-known sources. Malicious files are often " +
            "disguised as free tools or cracked software. If an installer asks you to disable your " +
            "antivirus, treat that as a serious red flag.";

    }
}
